### ISSUE TITLE
GREY OUT BUTTON PLEASE

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/generic-solution#141]
What if I press the ADD GROUPS AND PERMISSIONS button twice? Maybe I am multi tasking and not paying attention to what's happening below the button, then I may press the button again. What happens then? Can gray out button please? Thanks!

<img width="341" alt="image" src="https://user-images.githubusercontent.com/35781691/145434290-51c8896b-dcd2-4609-bd86-3d6ccc99725c.png">

**Comment by mikezimm** [comment]
@McDKirra ,
Whahooo!  praise the sun!
Issue will be resolved in the next web part update :)
